# Generated by Django 4.2.9 on 2024-01-14 07:06

from django.db import migrations, models
import habits.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100, verbose_name='место выполнения')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='время начала')),
                ('action', models.CharField(max_length=100, verbose_name='действие')),
                ('is_nice', models.BooleanField(blank=True, default=False, null=True, verbose_name='приятная')),
                ('interval', models.CharField(choices=[('ежедневно', 'ежедневно'), ('раз в неделю', 'раз в неделю'), ('раз в 4 дня', 'раз в 4 дня'), ('раз в 3 дня', 'раз в 3 дня'), ('раз в 2 дня', 'раз в 2 дня')], default='ежедневно', max_length=50, verbose_name='периодичность')),
                ('reward', models.CharField(blank=True, max_length=300, null=True, verbose_name='вознаграждение')),
                ('duration', models.DurationField(validators=[habits.validators.validate_duration], verbose_name='продолжительность')),
                ('is_public', models.BooleanField(default=False, verbose_name='публичная')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
                'ordering': ('id',),
            },
        ),
    ]
