# Generated by Django 4.2.9 on 2024-01-14 23:26

import datetime
from django.db import migrations, models
import habits.validators


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=120), validators=[habits.validators.validate_duration], verbose_name='продолжительность'),
        ),
    ]
