# Generated by Django 4.2.9 on 2024-01-14 23:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_habit_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='время начала'),
        ),
    ]
