# Generated by Django 4.2.9 on 2024-01-15 00:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_alter_habit_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='interval',
            field=models.CharField(choices=[(datetime.timedelta(days=1), 'ежедневно'), (datetime.timedelta(days=2), 'раз в 2 дня'), (datetime.timedelta(days=3), 'раз в 3 дня'), (datetime.timedelta(days=7), 'раз в неделю')], default=datetime.timedelta(days=1), max_length=50, verbose_name='периодичность'),
        ),
    ]
