# Generated by Django 4.2.9 on 2024-01-15 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_alter_habit_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='interval',
            field=models.CharField(choices=[('daily', 'ежедневно'), ('once in 2 days', 'раз в 2 дня'), ('once in 2 days', 'раз в 3 дня'), ('weekly', 'раз в неделю')], default='daily', max_length=50, verbose_name='периодичность'),
        ),
    ]
