# Generated by Django 4.2.9 on 2024-01-15 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0006_alter_habit_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='interval',
            field=models.CharField(choices=[('ежедневно', 'ежедневно'), ('раз в 2 дня', 'раз в 2 дня'), ('раз в 3 дня', 'раз в 3 дня'), ('раз в неделю', 'раз в неделю')], default='ежедневно', max_length=50, verbose_name='периодичность'),
        ),
    ]
