# Generated by Django 4.2.9 on 2024-01-16 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0007_alter_habit_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='start_time',
            field=models.DateTimeField(verbose_name='время начала'),
        ),
    ]
