# Generated by Django 4.2.9 on 2024-01-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0008_alter_habit_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='interval',
            field=models.CharField(choices=[('ежедневно', 'ежедневно'), ('раз в 2 дня', 'раз в 2 дня'), ('раз в 3 дня', 'раз в 3 дня'), ('еженедельно', 'еженедельно')], default='ежедневно', max_length=50, verbose_name='периодичность'),
        ),
    ]
